// ============================================================
// LINGUATRIP — Dane gry (MVP: Londyn, 7 dni)
// ============================================================
import type { DestinationConfig, Badge, Scenario, Day } from './types';

// ---- ODZNAKI ----
export const BADGES: Badge[] = [
  {
    id: 'first_words',
    name: 'First Words',
    description: 'Ukończ pierwszy scenariusz',
    icon: '🗣️',
    condition: 'complete_first_scenario',
  },
  {
    id: 'perfect_day',
    name: 'Perfect Day',
    description: 'Zdobądź 3 gwiazdki we wszystkich scenach jednego dnia',
    icon: '🌟',
    condition: 'three_stars_all_day',
  },
  {
    id: 'sharp_ears',
    name: 'Sharp Ears',
    description: 'Odpowiedz poprawnie na 10 pytań słuchowych z rzędu',
    icon: '👂',
    condition: 'listening_streak_10',
  },
  {
    id: 'wordsmith',
    name: 'Wordsmith',
    description: 'Napisz 20 poprawnych zdań w trybie wolnej odpowiedzi',
    icon: '✍️',
    condition: 'free_answer_20',
  },
  {
    id: 'week_warrior',
    name: 'Week Warrior',
    description: 'Graj 7 dni z rzędu',
    icon: '🔥',
    condition: 'streak_7',
  },
  {
    id: 'pub_quiz_champ',
    name: 'Pub Quiz Champion',
    description: 'Wygraj pub quiz z maksymalnym wynikiem',
    icon: '🎯',
    condition: 'pub_quiz_perfect',
  },
  {
    id: 'crisis_manager',
    name: 'Crisis Manager',
    description: 'Ukończ Dzień 6 (kradzież) z wynikiem powyżej 80%',
    icon: '🚨',
    condition: 'day6_80_percent',
  },
  {
    id: 'globe_trotter',
    name: 'Globe Trotter',
    description: 'Odblokuj drugą destynację',
    icon: '🌍',
    condition: 'unlock_second_destination',
  },
];

// ---- SCENARIUSZE — LONDYN DZIEŃ 1 ----
export const londonDay1Scenarios: Scenario[] = [
  {
    id: 'ldn_d1_s1',
    destinationId: 'london',
    dayNumber: 1,
    orderInDay: 1,
    title: 'Kontrola paszportowa',
    titleEN: 'Passport Control',
    description: 'Twój samolot właśnie wylądował. Idziesz korytarzem do kontroli paszportowej.',
    location: 'Heathrow Airport — Terminal 2',
    locationImage: '/images/heathrow-passport.jpg',
    duration: '~8 min',
    npcName: 'Officer Davies',
    npcImage: '/images/npc-officer.jpg',
    vocabularyFocus: ['purpose', 'visit', 'stay', 'address', 'business', 'tourism'],
    grammarFocus: 'Czas teraźniejszy — proste pytania i odpowiedzi',
    interactions: [
      {
        id: 'i1',
        type: 'cutscene',
        narration:
          'Samolot właśnie wylądował na Heathrow. Idziesz długim korytarzem do kontroli paszportowej. Kolejka porusza się szybko. Już Twoja kolej. Urzędnik patrzy na Ciebie poważnie.',
        image: '/images/heathrow-corridor.jpg',
        xpReward: 0,
      },
      {
        id: 'i2',
        type: 'choice',
        npcDialogue: 'Good afternoon. What\'s the purpose of your visit?',
        npcDialoguePL: 'Dzień dobry. Jaki jest cel Pana/Pani wizyty?',
        npcEmotion: 'neutral',
        choices: [
          {
            id: 'c1',
            text: 'Tourism. I\'m here for a week.',
            isCorrect: true,
            feedback: 'Doskonale! Krótka, jasna odpowiedź — dokładnie czego oczekuje urzędnik.',
            npcReaction: 'Very good. How long are you planning to stay?',
          },
          {
            id: 'c2',
            text: 'I come for tourism and I want to see London.',
            isCorrect: true,
            feedback: 'Poprawnie, ale trochę za długo — urzędnicy celni preferują zwięzłe odpowiedzi.',
            npcReaction: 'I see. And how long will you be staying?',
          },
          {
            id: 'c3',
            text: 'Yes, I visit.',
            isCorrect: false,
            feedback: 'To zdanie jest niepoprawne gramatycznie. Powiedz "Tourism" lub "I\'m here for tourism".',
            npcReaction: 'I\'m sorry, I didn\'t quite catch that. Are you here for tourism or business?',
          },
          {
            id: 'c4',
            text: 'Business trip.',
            isCorrect: false,
            feedback: 'Cel wizyty to turystyka, nie biznes. W passporcie masz wizę turystyczną!',
            npcReaction: 'A business trip? Do you have a work visa?',
          },
        ],
        xpReward: 20,
      },
      {
        id: 'i3',
        type: 'listening',
        audioText: 'How long are you planning to stay?',
        npcDialogue: 'How long are you planning to stay?',
        npcDialoguePL: 'Jak długo Pan/Pani planuje zostać?',
        npcEmotion: 'neutral',
        listeningChoices: [
          {
            id: 'l1',
            text: 'Pytanie o cel wizyty',
            isCorrect: false,
            feedback: 'Nie — "purpose" oznacza cel, a urzędnik pytał o czas pobytu.',
          },
          {
            id: 'l2',
            text: 'Pytanie o długość pobytu',
            isCorrect: true,
            feedback: 'Tak! "How long are you planning to stay?" = Jak długo planujesz zostać?',
          },
          {
            id: 'l3',
            text: 'Pytanie o adres hotelu',
            isCorrect: false,
            feedback: 'To pytanie o adres brzmiałoby: "Where are you staying?"',
          },
          {
            id: 'l4',
            text: 'Pytanie o posiadanie wizy',
            isCorrect: false,
            feedback: 'Pytanie o wizę brzmiałoby: "Do you have a visa?"',
          },
        ],
        xpReward: 25,
      },
      {
        id: 'i4',
        type: 'sentence_build',
        npcDialogue: 'And where will you be staying?',
        npcDialoguePL: 'A gdzie Pan/Pani będzie mieszkać?',
        npcEmotion: 'neutral',
        prompt: 'Powiedz urzędnikowi adres hotelu: Hilton, Paddington',
        words: ['staying', 'at', 'I\'ll', 'the', 'Hilton', 'Paddington', 'in', 'be'],
        correctSentence: 'I\'ll be staying at the Hilton in Paddington',
        timeLimit: 45,
        xpReward: 30,
      },
      {
        id: 'i5',
        type: 'fill_blank',
        npcDialogue: 'Enjoy your stay in London.',
        npcDialoguePL: 'Miłego pobytu w Londynie.',
        npcEmotion: 'happy',
        sentence: 'Thank you very ____!',
        options: ['much', 'many', 'lot', 'well'],
        correctFill: 'much',
        xpReward: 15,
      },
    ],
  },

  {
    id: 'ldn_d1_s2',
    destinationId: 'london',
    dayNumber: 1,
    orderInDay: 2,
    title: 'Szukanie wyjścia',
    titleEN: 'Finding the Exit',
    description: 'Przeszłeś kontrolę — teraz musisz znaleźć wyjście i taksówki. Na lotnisku roi się od tablic.',
    location: 'Heathrow Airport — Arrivals Hall',
    locationImage: '/images/heathrow-arrivals.jpg',
    duration: '~6 min',
    npcName: 'Emily',
    npcImage: '/images/npc-emily.jpg',
    vocabularyFocus: ['exit', 'taxi', 'straight', 'follow', 'signs', 'arrivals', 'terminal'],
    grammarFocus: 'Pytania o drogę: Where is...? How do I get to...?',
    interactions: [
      {
        id: 'i6',
        type: 'cutscene',
        narration:
          'Jesteś w hali przylotów. Tłum wita przyjeżdżających. Nagle widzisz młodą kobietę trzymającą tabliczkę z Twoim nazwiskiem — to Emily! Miała Cię odbierać z lotniska.',
        image: '/images/arrivals-hall.jpg',
        xpReward: 0,
      },
      {
        id: 'i7',
        type: 'choice',
        npcDialogue: 'Oh, hi! You must be from Poland! Welcome to London! First time here?',
        npcDialoguePL: 'Och, cześć! Musisz być z Polski! Witaj w Londynie! Pierwszy raz tutaj?',
        npcEmotion: 'friendly',
        choices: [
          {
            id: 'c5',
            text: 'Yes, it\'s my first time! I\'m so excited.',
            isCorrect: true,
            feedback: 'Świetnie! Naturalna, ciepła odpowiedź.',
            npcReaction: 'Oh brilliant! You\'re going to love it here!',
          },
          {
            id: 'c6',
            text: 'No, I was here before. Two years ago.',
            isCorrect: true,
            feedback: 'Poprawnie! Użyłeś czasu przeszłego — "I was here before".',
            npcReaction: 'Oh nice, so you know your way around a bit!',
          },
          {
            id: 'c7',
            text: 'Yes, I am first time.',
            isCorrect: false,
            feedback: '"I am first time" to błąd. Powiedz: "It\'s my first time" lub "Yes, this is my first time here".',
            npcReaction: 'Sorry, I\'m not sure I understood... Is this your first time in London?',
          },
        ],
        xpReward: 20,
      },
      {
        id: 'i8',
        type: 'listening',
        audioText: 'Follow me! The taxi rank is just outside, straight ahead and then turn left.',
        npcDialogue: 'Follow me! The taxi rank is just outside, straight ahead and then turn left.',
        npcDialoguePL: 'Chodź za mną! Postój taksówek jest zaraz za wyjściem, prosto, a potem w lewo.',
        npcEmotion: 'friendly',
        listeningChoices: [
          {
            id: 'l5',
            text: 'Taksówki są po prawej stronie',
            isCorrect: false,
            feedback: '"Turn left" = skręć w lewo, nie w prawo.',
          },
          {
            id: 'l6',
            text: 'Taksówki są prosto, potem w lewo',
            isCorrect: true,
            feedback: 'Dokładnie! "Straight ahead and then turn left" = prosto, potem w lewo.',
          },
          {
            id: 'l7',
            text: 'Taksówki są na zewnątrz budynku, daleko stąd',
            isCorrect: false,
            feedback: '"Just outside" oznacza tuż za wyjściem — nie daleko!',
          },
          {
            id: 'l8',
            text: 'Emily nie wie gdzie są taksówki',
            isCorrect: false,
            feedback: 'Emily powiedziała dokładnie gdzie są taksówki.',
          },
        ],
        xpReward: 25,
      },
      {
        id: 'i9',
        type: 'free_answer',
        npcDialogue: 'So, do you have a hotel booked already?',
        npcDialoguePL: 'Więc, masz już zarezerwowany hotel?',
        npcEmotion: 'friendly',
        prompt: 'Powiedz Emily, że masz zarezerwowany hotel Hilton w Paddington na 7 nocy.',
        exampleAnswer: 'Yes, I\'ve booked the Hilton in Paddington for seven nights.',
        keyWords: ['Hilton', 'Paddington', 'booked', 'nights', 'hotel'],
        xpReward: 35,
      },
    ],
  },

  {
    id: 'ldn_d1_s3',
    destinationId: 'london',
    dayNumber: 1,
    orderInDay: 3,
    title: 'Taksówka do hotelu',
    titleEN: 'Taxi to the Hotel',
    description: 'Wsiadasz do czarnej londyńskiej taksówki. Taksówkarz jest rozmowny — uwaga na cockney accent!',
    location: 'London Taxi — Heathrow to Paddington',
    locationImage: '/images/london-taxi.jpg',
    duration: '~10 min',
    npcName: 'Dave (taksówkarz)',
    npcImage: '/images/npc-taxi.jpg',
    vocabularyFocus: ['address', 'route', 'traffic', 'weather', 'small talk', 'fare', 'tip'],
    grammarFocus: 'Small talk — Present Simple, opinie, pogoda',
    interactions: [
      {
        id: 'i10',
        type: 'cutscene',
        narration:
          'Czarna londyńska taksówka zatrzymuje się przy krawężniku. Kierowca, Dave — gruby facet z sumiastymi wąsami i szerokim cockney accent — spogląda na Ciebie w lusterku.',
        image: '/images/taxi-interior.jpg',
        xpReward: 0,
      },
      {
        id: 'i11',
        type: 'choice',
        npcDialogue: 'Where to, mate?',
        npcDialoguePL: 'Dokąd, kolego?',
        npcEmotion: 'friendly',
        choices: [
          {
            id: 'c8',
            text: 'The Hilton, Paddington, please.',
            isCorrect: true,
            feedback: 'Idealnie! Krótko, jasno, grzecznie — dokładnie jak powinno brzmieć.',
            npcReaction: 'Right you are, Paddington Hilton it is! Hop in!',
          },
          {
            id: 'c9',
            text: 'Can you take me to the Hilton Hotel in Paddington?',
            isCorrect: true,
            feedback: 'Poprawnie i grzecznie! Pełne zdanie z "Can you take me to..."',
            npcReaction: 'Course I can, love! Buckle up!',
          },
          {
            id: 'c10',
            text: 'Hilton... Paddington... hotel.',
            isCorrect: false,
            feedback: 'To zrozumiałe, ale nie jest poprawnym zdaniem. Zawsze używaj pełnego zdania lub przynajmniej "The Hilton, Paddington, please".',
            npcReaction: 'Ha! Right, Paddington Hilton. No worries, I know the way.',
          },
        ],
        xpReward: 20,
      },
      {
        id: 'i12',
        type: 'listening',
        audioText: 'Lovely day innit? Not too cold for February, is it?',
        npcDialogue: 'Lovely day innit? Not too cold for February, is it?',
        npcDialoguePL: 'Piękny dzień, co nie? Niezbyt zimno jak na luty, prawda?',
        npcEmotion: 'friendly',
        listeningChoices: [
          {
            id: 'l9',
            text: 'Dave pyta o trasę do hotelu',
            isCorrect: false,
            feedback: '"Route" nie pojawia się w zdaniu. Dave mówi o pogodzie.',
          },
          {
            id: 'l10',
            text: 'Dave komentuje pogodę',
            isCorrect: true,
            feedback: 'Tak! "Lovely day" = piękny dzień. "Innit?" to cockney skrót od "isn\'t it?" — typowy dla Londynczyków!',
          },
          {
            id: 'l11',
            text: 'Dave pyta skąd przyjechałeś',
            isCorrect: false,
            feedback: 'Dave nie pyta o kraj pochodzenia — mówi o pogodzie.',
          },
          {
            id: 'l12',
            text: 'Dave narzeka na zimno',
            isCorrect: false,
            feedback: '"Not too cold" = niezbyt zimno — Dave mówi, że jest ładnie!',
          },
        ],
        xpReward: 25,
      },
      {
        id: 'i13',
        type: 'choice',
        npcDialogue: 'So where you from then? Poland? Russia?',
        npcDialoguePL: 'Skąd jesteś? Polska? Rosja?',
        npcEmotion: 'friendly',
        choices: [
          {
            id: 'c11',
            text: 'I\'m from Poland, actually. Warsaw.',
            isCorrect: true,
            feedback: '"Actually" dodaje lekko poprawiający ton — jakbyś mówił "właściwie to z Polski". Świetne użycie!',
            npcReaction: 'Warsaw! Lovely city. Had a fare there once — beautiful place!',
          },
          {
            id: 'c12',
            text: 'Poland. I come from Warsaw.',
            isCorrect: true,
            feedback: 'Poprawnie! Jasno i konkretnie.',
            npcReaction: 'Poland! Brilliant. Good workers, Poles. No offence!',
          },
          {
            id: 'c13',
            text: 'Yes, I am from Poland.',
            isCorrect: true,
            feedback: 'Poprawnie — choć "Yes" na początku jest lekko niezgrabne po tym jak Dave podał dwa kraje.',
            npcReaction: 'Poland, lovely! Welcome to London then!',
          },
        ],
        xpReward: 20,
      },
      {
        id: 'i14',
        type: 'sentence_build',
        npcDialogue: 'How long you staying for?',
        npcDialoguePL: 'Jak długo zostajesz?',
        npcEmotion: 'friendly',
        prompt: 'Powiedz że zostajesz na tydzień i bardzo chcesz zobaczyć Big Ben',
        words: ['week', 'staying', 'a', 'and', 'really', 'to', 'I\'m', 'for', 'see', 'I', 'want', 'Ben', 'Big'],
        correctSentence: 'I\'m staying for a week and I really want to see Big Ben',
        timeLimit: 50,
        xpReward: 30,
      },
      {
        id: 'i15',
        type: 'free_answer',
        npcDialogue: 'Here we are! The Hilton Paddington. That\'ll be £42.50, please.',
        npcDialoguePL: 'Proszę! Hilton Paddington. To będzie 42 funty 50 pensów.',
        npcEmotion: 'neutral',
        prompt: 'Zapłać taksówkarzowi i zostaw napiwek. Powiedz mu żeby zatrzymał resztę.',
        exampleAnswer: 'Here\'s fifty pounds. Keep the change.',
        keyWords: ['keep', 'change', 'pounds', 'thank'],
        xpReward: 35,
      },
    ],
  },
];

// ---- DZIEŃ 1 ----
export const londonDay1: Day = {
  destinationId: 'london',
  dayNumber: 1,
  title: 'Przylot — Witaj w Londynie!',
  titleEN: 'Arrival — Welcome to London!',
  storyDescription:
    'Twój samolot wylądował na Heathrow. Musisz przejść kontrolę paszportową, znaleźć wyjście i złapać taxi do hotelu. Na lotnisku spotykasz Emily — miłą Angielkę, która będzie Twoim przewodnikiem przez całą grę.',
  locationImage: '/images/heathrow-hero.jpg',
  scenarios: londonDay1Scenarios,
  bonusChallenge: {
    title: 'Rozmowa z Emily o Polsce',
    description: 'Emily pyta Cię o Polskę. Opowiedz jej 3 ciekawostki o swoim kraju.',
    xpReward: 50,
  },
};

// ---- KONFIGURACJA DESTYNACJI ----
export const DESTINATIONS: DestinationConfig[] = [
  {
    id: 'london',
    city: 'Londyn',
    country: 'Wielka Brytania',
    language: 'Angielski',
    flag: '🇬🇧',
    description: '7 dni w Londynie. Walcz z kontrolą paszportową, zgub się w metrze i uratuj swój skradziony portfel!',
    mapPosition: { x: 38, y: 28 },
    isUnlocked: true,
    totalDays: 7,
    days: [londonDay1],
  },
  {
    id: 'berlin',
    city: 'Berlin',
    country: 'Niemcy',
    language: 'Niemiecki',
    flag: '🇩🇪',
    description: '7 dni w Berlinie. Historia, kultura i berlińska scena muzyczna — wszystko po niemiecku.',
    mapPosition: { x: 51, y: 27 },
    isUnlocked: false,
    totalDays: 7,
  },
  {
    id: 'madrid',
    city: 'Madryt',
    country: 'Hiszpania',
    language: 'Hiszpański',
    flag: '🇪🇸',
    description: '7 dni w Madrycie. Flamenco, tapas i niekończące się słońce — aprende español!',
    mapPosition: { x: 34, y: 47 },
    isUnlocked: false,
    totalDays: 7,
  },
  {
    id: 'paris',
    city: 'Paryż',
    country: 'Francja',
    language: 'Francuski',
    flag: '🇫🇷',
    description: '7 dni w Paryżu. Wieża Eiffela, kawiarnie i francuska elegancja — bonjour le monde!',
    mapPosition: { x: 42, y: 36 },
    isUnlocked: false,
    totalDays: 7,
  },
];

// ---- HISTORIA LONDYNU (wszystkie 7 dni — streszczenia) ----
export const LONDON_DAYS_OVERVIEW = [
  {
    day: 1,
    emoji: '✈️',
    title: 'Przylot',
    titleEN: 'Welcome to London',
    subtitle: 'Kontrola paszportowa, wyjście z lotniska, taxi',
    isAvailable: true,
  },
  {
    day: 2,
    emoji: '🏨',
    title: 'Hotel',
    titleEN: "Something's wrong with my room",
    subtitle: 'Check-in, reklamacja, kolacja w restauracji',
    isAvailable: false,
  },
  {
    day: 3,
    emoji: '🗺️',
    title: 'Miasto',
    titleEN: "I'm completely lost",
    subtitle: 'Oyster Card, pytanie o drogę, spotkanie z Emily',
    isAvailable: false,
  },
  {
    day: 4,
    emoji: '🛍️',
    title: 'Zakupy',
    titleEN: 'Does this come in a different size?',
    subtitle: 'Camden Market, sklep, zwrot towaru',
    isAvailable: false,
  },
  {
    day: 5,
    emoji: '🍺',
    title: 'Ludzie',
    titleEN: 'Fancy a pint?',
    subtitle: 'Pub, small talk, pub quiz',
    isAvailable: false,
  },
  {
    day: 6,
    emoji: '🚨',
    title: 'Kryzys',
    titleEN: "My wallet's gone!",
    subtitle: 'Policja, telefon do banku, pożyczka od Emily',
    isAvailable: false,
  },
  {
    day: 7,
    emoji: '👋',
    title: 'Pożegnanie',
    titleEN: "I'll definitely come back",
    subtitle: 'Lotnisko, epilog, podsumowanie',
    isAvailable: false,
  },
];
